In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [5]:
df = pd.read_csv("../data/raw/supervised_dataset.csv")

In [6]:
print(df.shape)

(1699, 12)

In [7]:
df.columns.tolist()

['Unnamed: 0',
 '_id',
 'inter_api_access_duration(sec)',
 'api_access_uniqueness',
 'sequence_length(count)',
 'vsession_duration(min)',
 'ip_type',
 'num_sessions',
 'num_users',
 'num_unique_apis',
 'source',
 'classification']

In [8]:
df.dtypes

Unnamed: 0                          int64
_id                                   str
inter_api_access_duration(sec)    float64
api_access_uniqueness             float64
sequence_length(count)            float64
vsession_duration(min)              int64
ip_type                               str
num_sessions                      float64
num_users                         float64
num_unique_apis                   float64
source                                str
classification                        str
dtype: object

In [9]:
df.isnull().sum()

Unnamed: 0                        0
_id                               0
inter_api_access_duration(sec)    4
api_access_uniqueness             4
sequence_length(count)            0
vsession_duration(min)            0
ip_type                           0
num_sessions                      0
num_users                         0
num_unique_apis                   0
source                            0
classification                    0
dtype: int64

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1699 entries, 0 to 1698
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      1699 non-null   int64
 1   _id                             1699 non-null   str
 2   inter_api_access_duration(sec)  1695 non-null   float64
 3   api_access_uniqueness           1695 non-null   float64
 4   sequence_length(count)          1699 non-null   float64
 5   vsession_duration(min)          1699 non-null   int64
 6   ip_type                         1699 non-null   str
 7   num_sessions                    1699 non-null   float64
 8   num_users                       1699 non-null   float64
 9   num_unique_apis                 1699 non-null   float64
 10  source                          1699 non-null   str
 11  classification                  1699 non-null   str
dtypes: float64(6), int64(2), str(4)
memory usage: 159.4 KB

In [11]:
df.describe(include="all")

,Unnamed: 0,_id,inter_api_access_duration(sec),api_access_uniqueness,sequence_length(count),vsession_duration(min),ip_type,num_sessions,num_users,num_unique_apis,source,classification
count,1699.00000,1699,1695.000000,1695.000000,1699.000000,1.699000e+03,1699,1699.000000,1699.000000,1699.000000,1699,1699
unique,NaN,1678,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,2
top,NaN,496f878b-8444-3715-bd7c-75c19cbfc124,NaN,NaN,NaN,NaN,default,NaN,NaN,NaN,E,normal
freq,NaN,4,NaN,NaN,NaN,NaN,1542,NaN,NaN,NaN,1499,1106
mean,849.00000,NaN,1.501123,0.173226,61.648982,6.028341e+03,NaN,564.726898,406.263685,67.246616,NaN,NaN
std,490.60337,NaN,21.697558,0.283641,205.803273,4.665042e+04,NaN,1179.931200,960.718580,82.189214,NaN,NaN
min,0.00000,NaN,0.000003,0.001200,0.000000,1.000000e+00,NaN,2.000000,1.000000,0.000000,NaN,NaN
25%,424.50000,NaN,0.000707,0.009199,9.984756,6.300000e+01,NaN,5.000000,1.000000,14.000000,NaN,NaN
50%,849.00000,NaN,0.002574,0.018717,17.095238,1.950000e+02,NaN,164.000000,141.000000,37.000000,NaN,NaN
75%,1273.50000,NaN,0.024579,0.230769,41.349478,3.711500e+03,NaN,446.500000,308.500000,90.000000,NaN,NaN
max,1698.00000,NaN,852.929250,1.000000,3303.000000,1.352948e+06,NaN,9299.000000,8447.000000,524.000000,NaN,NaN

In [12]:
df.columns

Index(['Unnamed: 0', '_id', 'inter_api_access_duration(sec)',
       'api_access_uniqueness', 'sequence_length(count)',
       'vsession_duration(min)', 'ip_type', 'num_sessions', 'num_users',
       'num_unique_apis', 'source', 'classification'],
      dtype='str')

In [13]:
df["label"].value_counts()

KeyError: 'label'

In [14]:
df.columns.tolist()

['Unnamed: 0',
 '_id',
 'inter_api_access_duration(sec)',
 'api_access_uniqueness',
 'sequence_length(count)',
 'vsession_duration(min)',
 'ip_type',
 'num_sessions',
 'num_users',
 'num_unique_apis',
 'source',
 'classification']

In [15]:
df.head()

,Unnamed: 0,_id,inter_api_access_duration(sec),api_access_uniqueness,sequence_length(count),vsession_duration(min),ip_type,num_sessions,num_users,num_unique_apis,source,classification
0,0,1f2c32d8-2d6e-3b68-bc46-789469f2b71e,0.000812,0.004066,85.643243,5405,default,1460.0,1295.0,451.0,E,normal
1,1,4c486414-d4f5-33f6-b485-24a8ed2925e8,0.000063,0.002211,16.166805,519,default,9299.0,8447.0,302.0,E,normal
2,2,7e5838fc-bce1-371f-a3ac-d8a0b2a05d9a,0.004481,0.015324,99.573276,6211,default,255.0,232.0,354.0,E,normal
3,3,82661ecd-d87f-3dff-855e-378f7cb6d912,0.017837,0.014974,69.792793,8292,default,195.0,111.0,116.0,E,normal
4,4,d62d56ea-775e-328c-8b08-db7ad7f834e5,0.000797,0.006056,14.952756,182,default,272.0,254.0,23.0,E,normal

In [16]:
df["classification"].value_counts()

classification
normal     1106
outlier     593
Name: count, dtype: int64

In [17]:
df["classification"].value_counts()

classification
normal     1106
outlier     593
Name: count, dtype: int64